title: Rohit Mukherjee, Ph.D.
author: Rohit Mukherjee
url: https://rohitmukherjee.space
description: >
  Rohit Mukherjee develops machine learning methods and satellite datasets for
  flooding, surface water, urban vegetation, and climate research at PNNL.

exclude:
  - vendor
  - bin
  - README.md
  - review.html
  - review-decisions.json
  - Gemfile
  - Gemfile.lock

permalink: /:slug
favicon: "./logo.png"
favicon_emoji: "🌎"

highlighter: rouge

sass:
  style: :compressed

site_options:
  show_description: false
  show_navbar: true
  show_footer: true
