title: Rohit Mukherjee, Ph.D.
author: Rohit Mukherjee
url: www.rohitmukherjee.space
description: >
  I am a postdoctoral researcher specializing in machine learning and deep learning
  for geospatial analysis, with projects spanning urban flooding, informal road
  detection, and global surface water mapping.

permalink: /:slug
favicon: "./logo.png"

highlighter: rouge

sass:
  style: :compressed

site_options:
  show_description: false
  show_navbar: true
  show_footer: true
